### ISSUE TITLE
XMLSyntaxError: Entity 'nbsp' not defined

### ISSUE THREAD

**Issue by macmarrum** [nnako/freeplane-packer#2] opened 2022-12-17 11:28 UTC
Steps to reproduce
1. Open Freeplane
2. `Help->Tutorial`
3. `Tools->Open current map directory`
4. Copy the path to the file `freeplaneFunctions.mm`
5. Pack the file: `$ python packer.py pack <path-to-the-file>`

```python
---- PACKING FREEPLANE CONTAINER
Traceback (most recent call last):
  File "/home/data/git-repos/freeplane-packer/gui.py", line 179, in <module>
    app.pack(
  File "/home/data/git-repos/freeplane-packer/packer.py", line 200, in pack
    mindmap           = freeplane.Mindmap(self._mmpath)
  File "/home/data/git-repos/freeplane-packer/mmx.venv/lib/python3.10/site-packages/freeplane.py", line 263, in __init__
    self._mindmap = ET.parse(self._path, parser=xmlparser)
  File "src/lxml/etree.pyx", line 3538, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1902, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "/home/data/git-repos/freeplane-macmarrum/BIN/doc/freeplaneFunctions.mm", line 135
lxml.etree.XMLSyntaxError: Entity 'nbsp' not defined, line 135, column 101
```
___

```bash
$ pip list
Package      Version
------------ ---------
attrdict     2.0.1
colored      1.4.4
freeplane-io 0.7.0
Gooey        1.0.8.1
html2text    2020.1.16
lxml         4.9.1
numpy        1.23.5
Pillow       9.3.0
pip          22.3.1
psutil       5.9.4
pygtrie      2.5.0
setuptools   65.6.3
six          1.16.0
wheel        0.38.4
wxPython     4.2.0
```

**Comment by macmarrum** [comment] 2022-12-19 21:22
There's a workaround available: https://stackoverflow.com/questions/44254653/the-entity-nbsp-was-referenced-but-not-declared

**Comment by nnako** [comment] 2022-12-19 21:23
Hi @macmarrum , I created a [pull request](github.com/freeplane/freeplane/pull/897) to solve this problem on the Freeplane project. As by using `&nbsp;` within XML files renders these "invalid", the solution should be worked out over there instead of creating workarounds at different places around Freeplane.

As soon, as the pull request is evaluated (and hopefully accepted), I will close this particular issue within this project.

Thanks.

**Comment by nnako** [comment] 2022-12-19 21:30
> There's a workaround available: https://stackoverflow.com/questions/44254653/the-entity-nbsp-was-referenced-but-not-declared

yes, this seems to be a "solution", here are some more:

https://stackoverflow.com/questions/19974909/xml-non-breaking-space
https://stackoverflow.com/questions/31210655/nbsp-text-not-handled-by-the-lxml
https://bugs.launchpad.net/lxml/+bug/1936579

But all of them just give an "idea" which unfortunately does not solve the problem in my particular implementation, as I want to avoid tweaking the original source ".mm" file. Freeplane claims to use proper XML (since about `v1.5.x` or later). The solution should first be implemented from there. If that doesn't work out, I will try to solve it, here or within the `freeplane-python-io` project.

**Comment by macmarrum** [comment] 2022-12-19 21:30
I am sorry to disappoint you, but your pull request won't fix the issue. It only masks it temporarily for a single file.

It is Freeplane itself that puts `&nbsp;` in the `html` of its nodes.

You can see it by creating a new node with the text `a b c`, and then making `b` bold (select it and `Ctrl+B`). Then `Edit->Node core->Edit node core in dialog`, switch to `HTML Code view` to see

```html
<html>
  <head>
    
  </head>
  <body>
    <p>
      a <b>b</b>&nbsp;c
    </p>
  </body>
</html>
```

**Comment by nnako** [comment] 2022-12-19 21:33
I don't think that Freeplane inserts the `&nbsp;`. Freeplane inserts `&#160;`, which is to encode NON-BREAKING SPACES. This is my observation.

It might be the case that there are some more single files to be "corrected". I have NEVER had this issue before. And I have been heavily working with file parsing and Freeplane for more than 15 years, now ;-) .

But, as I said, I will try to push the solution on the Freeplane side. If it doesn't work out, I will try to find a workaround on my side.

**Comment by macmarrum** [comment] 2022-12-19 21:36
You must be using a different Freeplane than I am.

Have you tried the steps I described? Could you please share the html code that Freeplane created?

**Comment by nnako** [comment] 2022-12-19 21:47
Hi @macmarrum , this is what I get within the editor when I follow your sequence from the comment above:

```
<html>
  <head>
    <style type="text/css">
      <!--
        body { font-family: Segoe UI; font-size: 12pt; color: #000000; background-color: #ffffff }
        p { margin-top: 0 }
      -->
    </style>
    
  </head>
  <body>
    <p>
      a <b>b</b>&#160;c
    </p>
  </body>
</html>
```

And it is also what I see within the ".mm" file when I open it after save by Freeplane, except for the "oddity" that the `head` portion is empty within the Freeplane file (opened by Notepad++):

```
<html>
  <head>
    
  </head>
  <body>
    <p>
      a <b>b</b>&#160;c
    </p>
  </body>
</html>
```

**Comment by macmarrum** [comment] 2022-12-19 21:55
Yep, it's different than my Freeplane version, i.e. 1.10.6.
And I've seen nbsp for quite some time, probably in 1.9.x too.

**Comment by nnako** [comment] 2022-12-19 22:01
I was working with lower versions of Freeplane. Mostly with `v1.3.15` as within my company, higher versions are not permitted / granted (for whatever reasons), and I didn't want to run into compatibility issues caused by mixing versions when trying to share mindmaps.

Very interesting.

So, I might try to ask the Freeplane devs to go back to the XML representation implemented within older Freeplane versions, at least concerning the XML encoding of NON-BREAKING SPACES. Because, as I said, `&nbsp` does not seem to be considered proper XML.

When looking at the file "freeplaneFunctions.mm" (the example you found), all the older nodes use `&#160;` for encoding NBSP. Only the newer ones seem to use `&nbsp;` as they were created using a more recent Freeplane editor version. So, there is a mix within the files. But I doubt, that anybody would want to spend time on details like these, as they get visible only outside Freeplane...

Thanks for your efforts.

**Comment by nnako** [comment] 2022-12-20 10:47
@macmarrum 

I've just implemented a workaround in the [freeplane-python-io](https://pypi.org/project/freeplane-io/) module. Please use and update to the current version `v0.7.1` and the XML mismatch shouldn't cause any problems, anymore.

Thanks.

**Comment by macmarrum** [comment] 2022-12-20 20:04
Excellent!
I'll give it a try and report back

**Comment by macmarrum** [comment] 2022-12-20 21:20
Looks good :+1: 
Thanks

**Closed as completed** 2022-12-20 22:06 UTC
